### ISSUE TITLE
how to convert LST uint16 to float

### ISSUE THREAD

**Issue by khegewisch** [Google-Drought/WebInterface#102]
I don't see if very clear from documentation on how to convert uint16 to float in LST MODIS variable
and what units that would even get you. 

I did find this post: 
http://gis.stackexchange.com/questions/72524/how-do-i-convert-the-lst-values-on-the-modis-lst-image-to-degree-celsius

So I'm using the conversion 
degK = 0.002*uint16

**Comment by cgmorton** [comment]
For future reference:
https://lpdaac.usgs.gov/products/modis_products_table/mod11a2
