### ISSUE TITLE
Landsat EVI doesn't seem to working correctly

### ISSUE THREAD

**Issue by khegewisch** [Google-Drought/WebInterface#104]
Not convinced that EVI for Landsat5/8 is working correctly.

http://drought-monitor3.appspot.com?p3display=none&p5display=none&minDate=1979-01-01&yearStartClim=1984&yearEndClim=2011&varUnits=&chartType=column&maxYear=2015&SWLat=40.0&yearEnd=2015&p7display=none&token=1d2037f489d4f1e5db6391d6e3d4e050&p6display=none&domainType=full&maxColorbar=0.9&statistic=Median&minColorbar=-0.1&dateStart=2011-05-03&palette=ffffe5,f7fcb9,d9f0a3,addd8e,78c679,41ab5d,238443,006837,004529&SWLong=-111.0&mapid=cd2630f1aa3217499bbdd50a55ecce9d&state=California&mapCenterLongLat=-114.2632,37.3698&mapzoom=5&pointsLongLat=&p2check=checked&anomOrValue=value&colorbarsize=9&p1check=checked&p2display=none&p1display=block&timeSeriesCalc=days&variable=5EVI&p7check=checked&p4check=checked&p3check=checked&NELong=-95.0&p2=-114.2632,37.3698&p3=-114.2632,37.3698&p1=-114.2632,37.3698&p7=-114.2632,37.3698&p4=-114.2632,37.3698&p5=-114.2632,37.3698&p6=-114.2632,37.3698&colorbarmap=YlGn&layer=none&maxDate=2015-02-17&p5check=checked&kmlurl=&NELat=45.0&colorbarLabel=EVI&marker_colors=['blue', 'green', 'orange', 'purple', 'yellow', 'pink', 'red']&kmloption=&dateEnd=2011-11-01&units=metric&opacity=0.7&product=5&yearStart=1979&p6check=checked&minYear=1984&p4display=none

**Comment by cgmorton** [comment]
Yeah, that looks way off.  I bet the band numbering using expressions is 0 based and I used 1 based.

**Comment by cgmorton** [comment]
Yup: https://ee-api.appspot.com/62c5889ab6e3c204e00f4eddc77fb76d

All the band numbers in the EVI expressions need to be decreased by 1.  Although it might be better to switch to the band names instead.

**Comment by cgmorton** [comment]
I modified the expression to use band names in collectionMethods.py.  The output looks better to me but I'll let you close it if you agree with the fix.
