### ISSUE TITLE
Add Download of a Rectangle of Map Data

### ISSUE THREAD

**Issue by khegewisch** [Google-Drought/WebInterface#105]
Reinstantiate the rectangle feature on the map.. and the form/listeners to go along with it. 

With the rectangle coordinates, 
figure out how to get a URL for the download of the data. 

Could either set up emailing this URL to the user when it's ready.... 
or some other feature to enable downloading of the data. 

Charles has an example here
 
https://ee-api.appspot.com/cc9c7e47415c2ad50a9ba2e8210e884f

**Comment by khegewisch** [comment]
Download Data section has been added. 
Working Rectangle has been added to the map, with listeners that work. 

For the downloading of images... 
We are encouraged to use Export.Image instead of urlDownload: 
https://sites.google.com/site/earthengineapidocs/basic-image-manipulation/uploading-and-downloading-images-1

I tried a sample playground script:
https://ee-api.appspot.com/cf08da691d7127e911e6f734e019dd4e
and if you RUN it.. you will see a RUN button under Tasks. 
We executed this.. and waited for 7 minutes... hoping to see a URL or something. 

What we got instead.. was an error message.. saying that Export.image() couldn't be used for gRIDMET because the values were floats. ????


![weirderror](https://cloud.githubusercontent.com/assets/7798273/6380603/98229cb6-bcef-11e4-90d9-e96239096385.png)

**Comment by cgmorton** [comment]
One issue you may have with using Export.image() is indicated on the first line of Export.image() section in the first link you provided: "Earth Engine imagery can be exported to Google Drive or Google Maps Engine using the Export.image() function".  When you use the Export.image() function it doesn't provide a URL you can download and instead tries to save the image in your Google Drive.  To use this approach we would have to require the user to have a Gmail acccount and probably verify it somehow (like when you login to appspot?).

For your playground script, after running the task, check your Google Drive and the image should be in there.  I didn't change anything in the example you provided and it showed up after about a minute.

Katherine, let me know if there is someway I can help with trying getDownloadURL, but I think you can probably get it working a lot faster than I can!

**Comment by khegewisch** [comment]
Charles wrote: 
Based on some very minimal testing (sorry in advance if there are bugs/errors!) you can set a palette using .visualize() but this seems to return 3 TIF images (one for each RGB band) instead of a single image.  If I don't set a palette, I get a grayscale TIF back that looks correct.  If we don't use visualize() at all, the TIF file is still correct but without any color scaling (I brought it into QGIS on my mac at home and the pixel values are good even though it looks all white).  Finally, you can also pass a format parameter to getDownloadURL (mentioned in the group discussion but I don't see it in the documentation anywhere) so you can have the output image be a JPG, which does have the correct palette and color scaling in a single image.

https://ee-api.appspot.com/5ee4c4763fb9ec7b3b152142db5e8e2a


and for getDownloadURL: 

The other way I would find this is directly through the earthengine-api source code (https://code.google.com/p/earthengine-api/source/browse/python/ee/image.py).

**Comment by khegewisch** [comment]
Download is now working... for just the .tfw... with blank .tif. 
Added formats too.. 

but.. I think there is going to be a problem. 
I just read
getDownloadUrl()
Gets the URL that can be used to download the file. Only users with permission to open the file in Google Drive can access the URL.

So even though I can use the URL that I get, I think another user would need to be logged into their google account. We may have to just add the google authentication login to our site.
