### ISSUE TITLE
New Error on TimeSeries 

### ISSUE THREAD

**Issue by khegewisch** [Google-Drought/WebInterface#107]
I'm now getting a new weird error.... after a submission for a lot of time series data. 

Here... I did the following

![request](https://cloud.githubusercontent.com/assets/7798273/6341089/85dfdba6-bb7b-11e4-9a72-08de8c990199.png)

And got this.. 
![weirdnewerror](https://cloud.githubusercontent.com/assets/7798273/6341092/8ca087b0-bb7b-11e4-9b4b-0e192787f8bf.png)

So this isn't a time out or a memory error.. but a server error. ?
Need to catch this.. and serve up our own page on this.

**Comment by bdaudert** [comment]
This might be closed after threading for time series was implemented today. I tested all day and did not see this error at all.

**Comment by bdaudert** [comment]
Not closed! Encountered this morning for a Landsat three point request over 5 years.
 In the developers console logs, this error shows as a

DeadlineExceededError

I thought we had taken care of this one?

**Comment by bdaudert** [comment]
Threading per point and time slice took care of this issue
