### ISSUE TITLE
Add colormap USDM

### ISSUE THREAD

**Issue by khegewisch** [Google-Drought/WebInterface#108]
Add another colormap under a heading of 'Custom'
for USDM color ramp (US Drought Monitor)

This color map is 
Yellow, Tan, Orange, Red, Dark Red
technically 5 colors.. but we need to add ability to put in 3 to 9 colors in our code. 

![usdmcolormap](https://cloud.githubusercontent.com/assets/7798273/6341560/8127d686-bb80-11e4-9379-0ffc5bd37834.png)

**Comment by khegewisch** [comment]
Looks like: 

Yellow = #ffff00
Tan = #fcd37f
Orange = #ffaa00
Red = #e60000
Dark Red = #730000

**Comment by khegewisch** [comment]
Most of this is done... only thing left to do.. is to limit the colorbar sizes to just 6 (not 3-9).. when this colormap is chosen to make it clear the user has only one choice. 

Currently have a listener in /media/myjs/formlistener_colorbar.js

need to change this so it removes all buy 6 on the colorbar size when USDM/invUSDM is chosen.

**Comment by vansant** [comment]
Just pushed the update for this.
