### ISSUE TITLE
Custom KML/KMZ Layer Stays 

### ISSUE THREAD

**Issue by vansant** [Google-Drought/WebInterface#109]
After loading in a custom KML/KMZ layer it does not remove itself from the map when choosing none or any of the predefined regions.

Update required in formListener_layers.js

**Comment by khegewisch** [comment]
Donny commented out a line on the kml keyup and now I think this problem is solved.

**Comment by khegewisch** [comment]
Donny fixed this yesterday. 

Added a jQuery listener on getting a layer of 'None' and that worked... mysteriously.
