### ISSUE TITLE
Landing page: modal window

### ISSUE THREAD

**Issue by khegewisch** [Google-Drought/WebInterface#34]
it would be ideal if the landing page for our site... 
started at the modal window

#droughtHome

where the user can quickly click the x to get rid of it.. 
but this would be better than just a blank map.. with some options.. 

Perhaps.. there should be a beginning tutorial too... from this modal window..
or the option to just start using the tool.

**Comment by khegewisch** [comment]
http://foundation.zurb.com/forum/posts/3287-reveal-modal-window-on-page-load

**Comment by khegewisch** [comment]
in template/includes/scripts.php.... I tried this.. (didn't work though)


        

        <script type="text/javascript">

                $(document).ready(function() {

                        setTimeout( function() {

                                $('#droughtHome').click();

                                }, 2000);

                });

                

                

                

        </script>

**Comment by vansant** [comment]
I set the Drought Home modal to popup when the website loads.
