### ISSUE TITLE
landsat data source needs to be changed

### ISSUE THREAD

**Issue by khegewisch** [Google-Drought/WebInterface#47]
Charles suggested 
1) we remove Landsat 8 from our merging because it's bands are different than 4/5/7 and so values of NDVI are not comparable
2) instead of using 8-day composites, we use daily data and apply a cloud mask. 
This is different for our current system, so here was the suggested change in collection_methods.get_collection(): 
var landsat5_coll = ee.ImageCollection('LT5_L1T_TOA');

//Calculate NDVI and apply the basic ACCA cloud mask
function landsat457_ndvi_func (refl_toa_image) {
  var cloud_mask = ee.Algorithms.Landsat.simpleCloudScore(refl_toa_image)
    .select(['cloud']).lt(ee.Image.constant(50));
  refl_toa_image = refl_toa_image.mask(cloud_mask.mask(cloud_mask));
  return refl_toa_image.normalizedDifference(["B4","B3"])
    .clamp(-0.1,1).select([0], ['NDVI']); }
var landsat5_ndvi_coll = landsat5_coll.map(landsat457_ndvi_func);

**Comment by cgmorton** [comment]
The other option would be to use a different marker symbol to show which Landsat each value came from.  Then it would be more obvious why there might be differences in the values.  This could also come in handy if we ever tried to integrate other sensors.
