### ISSUE TITLE
 calendar issues: minDate , maxDatae and yearRange

### ISSUE THREAD

**Issue by khegewisch** [Google-Drought/WebInterface#48]
Need to change minYear from a template to a call to the form variable: 

maxDate: "-1d",
minDate: document.getElementById('minYear').value+"-01-01",
yearRange: document.getElementById('minYear').value+":2014",

**Comment by khegewisch** [comment]
yearRange: document.getElementById('minYear').value+":+0",

is the way to get range to current year.

**Comment by bdaudert** [comment]
This did not quite do it since datepicker is generated onload and needs to be updated dynamically afterwards. 
In the variable change formListener, I added
        $('.dateStart').datepicker( "option", "minDate", minYear + '-01-01');
        $('.dateStart').datepicker( "option", "yearRange", minYear + ':+0');
        $('.dateEnd').datepicker( "option", "minDate", minYear + '-01-01');
        $('.dateEnd').datepicker( "option", "yearRange", minYear + ':+0');

That seems to have solved the issue.

**Comment by bdaudert** [comment]
This seems to cause an instability with the datepicker

**Comment by bdaudert** [comment]
typo on js_datepicker.html found and fixed
