### ISSUE TITLE
Loaded data is 1 day offset from gridMet

### ISSUE THREAD

**Issue by khegewisch** [Google-Drought/WebInterface#63]
*John thinks that our data coming out in time series is 1 day offset from the actual gridMET data (and that on google cloud)… 

I have not checked that this is the case. 

I'm thinking that it might be caused by: 
*Charles doy_filter is a problem (though I thought I checked this)..
*code error due to python starts at index 0, not 1 ?

**Comment by cgmorton** [comment]
Is this the same issue that we emailed about this morning where we are passing highcharts the time as Unix time (seconds since Jan. 1st 1970) but then highcharts is using your local time for the display?  It would cause the data to look like it is one day earlier.

**Comment by khegewisch** [comment]
Yes.... although it is not highcharts,but googlecharts,right? 
Regardles, we are not handling the time range correctly with filterDate in our code... 

See for example.. 

https://ee-api.appspot.com/c8a9457c1dcf8ba11c684b3c37b447ae

Do you know why it is that when I filter by date 12/1 - 12/2, 
I only get data back from gridmet for 11/31?

I think there is something wrong with our interpretation of the dates in select date. 

For example, it seems that if we really want just 12/1, then we have to input 
12/02 - 12/03 into the selectDate function.

**Comment by cgmorton** [comment]
I think it is working correctly.  It looks like you are getting data back for 12/1 (in UTC time), which is then being interpreted to your local time zone so it shows up as 11/30.  Change the time zone on your computer to GMT and the x-axis will change to 12/1

**Comment by cgmorton** [comment]
It is a bit of a hack but you could also build a date string object (in a GMT/UTC timezone, not the local timezone) and attach it to each GRIDMET image as a property and then use that property as the x-axis label:
https://ee-api.appspot.com/a47818de22e80d36b622299b47a016cb

**Comment by khegewisch** [comment]
Tyler says: 
1) The default timezone is local. This is likely not a good option for web apps... I will bring this up with the team.
https://developers.google.com/chart/interactive/docs/reference#dateformatter
timeZone	The time zone in which to display the date value. This is a numeric value, indicating GMT + this number of time zones (can be negative). Date object are created by default with the assumed time zone of the computer on which they are created; this option is used to display that value in a different time zone. For example, if you created a Date object of 5pm noon on a computer located in Greenwich, England, and specified timeZone to be -5 (options['timeZone'] = -5, or Eastern Pacific Time in the US), the value displayed would be 12 noon.

2) The default system:time_start and system:time_end for the image based on 0 UTC. Perhaps that is not correct as well since gridMet has a -6Z offset.

**Comment by cgmorton** [comment]
Is the -6Z offset in the metadata anywhere?  If not then Simon probably didn't apply it.

**Comment by khegewisch** [comment]
After talking with Charles, we have agreed that a solution to this is: 

1) create a date object with a timeZone:0 (UTC) and put the startDate in this.. to avoid GAE defaulting to the user's time zone. Same for endDate.
2)   adding an extra time step unit (1 day for daily data, 1 hour for hourly data and maybe 16-days for a 16-day modis) to the endDate to avoid the exclusiveness of the endDate.
