### ISSUE TITLE
sharelink doesn't have current zoom/center

### ISSUE THREAD

**Issue by khegewisch** [Google-Drought/WebInterface#68]
*share Link button… needs the current zoom/center.. not that from the last POST.  

the problem is that shareLink is generated from form elements from last POST.. but the user 
can zoom/recenter before clicking the shareLInk. 

we need to just have shareLink have a quick look at current zoom/center in constructing the shareLink.

**Comment by bdaudert** [comment]
Britta: 
implemented code for that in templates/includes/scripts in zoom_changed and center_changed functions. 
	However, var sl = $('#shareLink').val();/ var sl = document.getElementById('shareLink').value are blank/undefined at all times (GET/POST). 
	Could this  because shareLink is defined in a modal window? 
        This means I can't dynamically update the shareLink. Not sure how to proceed…	Ideas?

**Comment by khegewisch** [comment]
shareLink is created in python and passed to the modal window via template. 
1) Let's not let the user modify the shareLink in the text box.. make it readonly: 
<input type="text" name="country" value="Norway" readonly>
2) I was thinking that upon clicking one of either GET MAP or GET TIMESERIES... 
we execute  a quick javascript function like this: 
<input type="submit" class="btn btn-large btn-primary pull-right" value="GET MAP"
					 form="form_map" onclick="document.getElementById('domainType').value='full';setZoomCenterInShareLink();"/>

 that alters the shareLink by find/replacing the zoom and mapcenter with the current zoom and mapcenter. This javascript function would look like this and be in scripts.js:

 function setZoomCenterInShareLink() {
                #get current mapzoom
               mapzoom = document.getElementById('mapzoom');
             #get current mapCenter
              mapCenterLongLat = document.getElementById('mapCenterLongLat').value;
             #get current shareLink
            shareLink= document.getElementById('shareLink').value;
           #shareLink is just a string that has within it... &mapzoom=5&  and &mapCenterLongLat=-112,42&
           shareLink = shareLink.replace('/mapzoom=/\d\d?/',
                                                         'mapzoom=''+mapzoom); #reg exp might be wrong
          shareLink = shareLink.replace('/mapCenterLongLat=/\d+(\.\d+),\d+(\.\d+)/'
                           ,'mapCenterLongLat='+mapCenterLonLat);#reg exp might be wrong
          #save back to the forms
          document.getElementById('shareLink').value=shareLink;
}

**Comment by bdaudert** [comment]
1. I made shareLink readonly.

2.  I update shareLink dynamically when map zoom or center is changed.  I did not have to add the  additional function to scripts since everything is handled in the map code.
