### ISSUE TITLE
Larger time series requests rendering rather slow

### ISSUE THREAD

**Issue by bdaudert** [Google-Drought/WebInterface#73]

**Comment by bdaudert** [comment]
We broke up larger requests into 5 year chunks to avoid the 2500 images limit per request. 

Another option suggested by Max was using the getDownloadURL() method. 
However, I don't see that method as an option for ee.imageCollection which is what we have.

Katherine suggested JSONP but I can't see how that could help us here.

**Comment by khegewisch** [comment]
Max's code in the playground for the getDownloadURL() is this: 
https://ee-api.appspot.com/e4be0a417d2294b23bb17302c000722a
====================
var gridmet = ee.ImageCollection("IDAHO_EPSCOR/GRIDMET").select(0);
var point = ee.Geometry.Point(-100.9863, 37.7186);
var features = ee.FeatureCollection(gridmet.map(function(img) {
  return ee.Feature(null, {'sample': img.reduceRegion('first', point, 1)});
}));
print(features.getDownloadURL('csv'));
====================
So he starts with an image collection just like we do, so this is a vision for how it might work... 
In collectionMethods.py: 
====================
In def get_time_series(template_values):
...
     points = ee.Feature.MultiPoint(pointsLongLatTuples);
...
     collection,collectionName,collectionLongName,product,variableShortName,notes=get_collection(var);
    
...
    #check if there is more than 2500 records requested here 
...
    if(yearRange<=5): #2500/365 =6.8 years is max records can be returned with getInfo()
       ...
    else:
          features = ee.FeatureCollection(gridmet.map(function(img) {
                           return ee.Feature(null, {'sample': img.reduceRegion('first', point, 1)});
                     }));         
                   timeSeriesURL =  features.getDownloadURL('json');
====================
I believe the timeSeriesURL would be like this: 
https://earthengine.googleapis.com/api/table?docid=1c2b3afb035a8c7080b147bb88cb4b97&token=40748a58e4bad5c827805f5aa5a82846
We would save the above timeSeriesURL in the template... .to pass to scripts.js: 

Then in scripts.js  inside the initialize() function, we'd do: 

#adds options with an empty series of data
    var options = {
        chart: {
            renderTo: 'container',
            type: 'spline'
        },
        series: [{}]
    };
   
    var url =  "{{ timeSeriesURL }}/jsonp.php?callback=?";
    $.getJSON(url,  function(data) {
        options.series[0].data = data;
        var chart = new Highcharts.Chart(options);
    });
====================

The above might not work.. but this is my vision of how MAYBE it works. 

-kch

**Comment by bdaudert** [comment]
I am having troubles reproducing your code in the python api
https://ee-api.appspot.com/e4be0a417d2294b23bb17302c000722a

My python attempt:

collection = ee.ImageCollection("IDAHO_EPSCOR/GRIDMET").filterDate('2000-01-01','2000-01-5').select('pr')
def reducer(img):
point = ee.Geometry.Point(-100.9863, 37.7186)
return ee.Feature(None, {'sample': img.reduceRegion('first', point, 1)})
features = ee.FeatureCollection(collection.map(reducer))
downloadUrl = features.getDownloadURL('csv')

gives me:
AttributeError: 'FeatureCollection' object has no attribute 'getDownloadURL'

**Comment by khegewisch** [comment]
Max wrote us: 

It's a naming bug on our side. In Python getDownloadURL is spelled getDownloadUrl - note the lowercase "rl". We'll fix it in one of the next updates so both versions work.

**Comment by bdaudert** [comment]
getdownloadUrl method is implemented now but we still see this issue persist. The issue could be the data formatting loop that gets the data ready to be rendered in highharts. With the way EE spits out the data (all points are in one list), I can't see a way to avoid the data loop.

**Comment by bdaudert** [comment]
Note to Britta: FIX: use map and zip to avoid looping when setting up js arrays!

x=[1,2,3];y=[4,5,6]
z = map(list,zip(x,y))
z= [[1,4],[2,5],[3,6]]
