### ISSUE TITLE
Dynamic default colorbar min/max values based on number of days for Totals/Sums

### ISSUE THREAD

**Issue by cgmorton** [Google-Drought/WebInterface#76]
It is a little confusing that the default colorbar values do not take into account the time period when using the Total/Sum method.  For example, map PET for 2014-01-01 to 2014-12-31 and a large majority of the pixels appear to have a value greater than the default of 800.

**Comment by khegewisch** [comment]
estimated the number of months 
and use this to give dynamic colorbar ranges for pet/ppt/wb

but... what I've done still might not be good enough.. 
first step, though.
