### ISSUE TITLE
dynamic progressbar

### ISSUE THREAD

**Issue by khegewisch** [Google-Drought/WebInterface#84]
John suggested.... if we know the user has selected data that will take some time to make.. 
we modify the progressbar.. to 'due to the amount of data selected, this will take a while'
something like that

**Comment by bdaudert** [comment]
For time series implemented  in formListener_points:
jQuery('#form_map').submit(function( event ) 

for maps implemented in templates/includes/scripts.

Katherine, feel fre to change the wording and the conditions. 
Right now, for map request they are set like this: 

if  calculation == values and date range > 5 years
     Message:
      'You asked for a large amount of data. 
      Please be patient while we process your request.'
else if calculation == clim/anom/... and date range > 1 year
    Message:
     'You asked for a large amount of data. 
      Please be patient while we process your request.'
else
    Message:
    "Processing Request"
