### ISSUE TITLE
min /max climatology are not being calculated correctly

### ISSUE THREAD

**Issue by khegewisch** [Google-Drought/WebInterface#85]
if one choose a day range.. and then chooses min/max statistic, they will get the min/max over that timeperiod. However for climatology, it is expected that we get the min/max over the day range for a single year.. and then average over all years. Currently the code is just taking min/max over all the years of that day range. This is incorrect.

**Comment by cgmorton** [comment]
Take mean over the years of the min over the days

**Comment by cgmorton** [comment]
Initial code is in the "min_max_climatology" branch.  It still needs lots of work, but check out the playground script for an example of the approach: https://ee-api.appspot.com/d18ab374e311df7880dcd4c01749b554
