### ISSUE TITLE
PET for Feb. 1st, 2015 is almost all null data

### ISSUE THREAD

**Issue by cgmorton** [Google-Drought/WebInterface#88]
The missing PET image is causing PET and WB to look bad for any time period that includes Feb 1st, 2015.  Need to check the raw GRIDMET data and if it is good then have Simon try to re-ingest the data.

**Comment by khegewisch** [comment]
There's something wrong with Feb 1st... tmax/tmin.. they are ~5 K. 
John has been informed.

This would affect PET.
