### ISSUE TITLE
EVI is being calculated using expressions and will fail if the Python EarthEngine API version is before 0.1.41

### ISSUE THREAD

**Issue by cgmorton** [Google-Drought/WebInterface#89]
The Python earthengine API being used for the website should be updated to the latest version (https://sites.google.com/site/earthengineapidocs/reference/api-changelog) or the EVI expression could be rewritten using math methods.

**Comment by khegewisch** [comment]
to check and update ee version: 
ip search earthengine-api

earthengine-api           - Earth Engine Python API
  INSTALLED: 0.1.37
  LATEST:    0.1.42

pip install earthengine-api --upgrade

**Comment by cgmorton** [comment]
Just in case you haven't seen it already, you can follow the changes to the Earth Engine API here:
https://sites.google.com/site/earthengineapidocs/reference/api-changelog

**Comment by khegewisch** [comment]
The above fix for updating seems to have worked.. as I now have 0.1.42. 
However, EVI is still broken. Error message is 

 File "/Users/katherine/temp/UofI/UofI/collectionMethods.py", line 362, in landsat457_evi_func
    return img.expression('(2.5 * (b(4) - b(3))) / (b(4) + 6 * b(3) - 7.5 * b(1) + 1)')\
  File "/Users/katherine/temp/UofI/UofI/ee/image.py", line 285, in expression
    'Image.parseExpression', expression, arg_name)
  File "/Users/katherine/temp/UofI/UofI/ee/apifunction.py", line 73, in call_
    return cls.lookup(name).call(*args, **kwargs)
  File "/Users/katherine/temp/UofI/UofI/ee/function.py", line 66, in call
    return self.apply(self.nameArgs(args, kwargs))
  File "/Users/katherine/temp/UofI/UofI/ee/function.py", line 79, in apply
    result = computedobject.ComputedObject(self, self.promoteArgs(named_args))
  File "/Users/katherine/temp/UofI/UofI/ee/function.py", line 109, in promoteArgs
    'Required argument (%s) missing to function: %s' % (name, self))
EEException: Required argument (vars) missing to function: Generates an algorithm from an arithmetic expression on images. By default
the generated algorithm takes one argument to denote the 'default' image.
Other variables in the expression are interpreted as image arguments that
will be passed to the returned algorithm. The bands of each image can be
accessed as image.band_name or image[0]. The bands of the default image are
available using the built-in function b(), as b(0) or b('band_name').  Both
b() and image[] allow multiple arguments, to specify multiple bands, such
as b(1, 'name', 3).  Calling b() with no arguments returns all bands of the
image.

Args:
  expression: The expression to parse.
  argName: The name of the default image argument.
  vars: The parameters the resulting algorithm should have, which
      must be a superset of the free variables in the expression,
      including the default image argument if it is used.

Ideas?

**Comment by cgmorton** [comment]
Landsat 5 and 8 EVI show up for me with the current version of the code.  Are you sure you copied the updated ee folder into your WebInterface folder (or are you using symbolic links)?
