### ISSUE TITLE
slider on transparency

### ISSUE THREAD

**Issue by khegewisch** [Google-Drought/WebInterface#91]
Justin would like the dropdown transparency choices to change to a slider. 

I tried bootstrap-slider.js
but it would not work for me to accomplish this.  (just got a text box instead of a slider)
http://seiyria.github.io/bootstrap-slider/
https://github.com/seiyria/bootstrap-slider

**Comment by khegewisch** [comment]
Do this in javascript with listeners on the variables.

https://developers.google.com/maps/documentation/javascript/reference#ImageMapType
map.overlayMapTypes[0].setOpacity(.25)

**Comment by vansant** [comment]
Added a slider after a map is rendered
