### ISSUE TITLE
Requesting two points from Modis/Landsat gives allocation error. 

### ISSUE THREAD

**Issue by khegewisch** [Google-Drought/WebInterface#99]
Requesting two points Modis/Landsat gives the allocation error. 
Running a request for seven points gives me the bad gateway error. 

Here is the python code converted to js

https://ee-api.appspot.com/e146ae9ede0cb6d00d48dd7041c1a01e

Note that in the playground I just get timeout errors. 
I can't reproduce allocation/bad gateway error.
To see that in action, you can play around here:
http://gd-britta.appspot.com/
in the time series tab. 
Try to request MODIS time series  data 2000 - 2015 for two points 
Here is an example of a successful run for one point:

http://tinyurl.com/mcrwbsz

If you click on the "Time Series" tab, you can see how the form was set. 

The python code equivalent to the js code is in the get_time_series function

https://github.com/Google-Drought/WebInterface/blob/development/processingMethods.py

**Comment by khegewisch** [comment]
Max wrote: 
> https://ee-api.appspot.com/e146ae9ede0cb6d00d48dd7041c1a01e

Here's a cleaned up version that succeeds in ~15 seconds on 2 points
when the queries run in parallel:

https://ee-api.appspot.com/6815cb78709ff55df2b799e6a262ac29

Change the coordinates a bit to avoid looking at the cached results.

For 7 points, it takes a retry or two to get the result, but it also
eventually comes back. Note that when you get a timeout (502 is the
same thing), the request is still running on EE - AppEngine just won't
let you wait longer. In that case you can retry the exact same request
and it will reconnect to the same running aggregation. You can also
try reducing the batch size (time step) to get results faster, but you
run the risk of hitting a request/aggregation quota.

**Comment by bdaudert** [comment]
Hi Max,
Can you tell me how do I concatenate the results?
The List.cat method doesn't seem to be working, maybe because samples is a
list of lists?

Thanks. Britta

https://ee-api.appspot.com/bc154538f78884cba0fed8f1f0b47db5

**Comment by bdaudert** [comment]
After implementation of threading, I did not see this error again.
